### ISSUE TITLE
fix: focus jumps to previous fields in collection

### ISSUE THREAD

**Issue by adam-sroka** [DigitalNutritionalAssessment/gibsonify#15]
When using Date/Time pickers or `DropDownButtonFormField`s in Collection, the focus jumps back to one of the previous `TextFormField`s, bringing up the keyboard as well, which is quite annoying.

https://user-images.githubusercontent.com/45038919/148658529-58b29f73-7560-4888-9ced-e8f47c1fdece.mp4

**Comment by adam-sroka** [comment]
The first step of this would be to replace the `DropdownMenuItem` widgets by `DropdownSearch` and to see if this is still the case, as we nevertheless want to move to `DropdownSearch` as it also fixes the blank item problem. If that won't fix the issue, then looking at `FocusNode`s might help.

**Comment by fpervaiz** [comment]
Fixed in #23 and verified by testing
