### ISSUE TITLE
fix: phone number validation

### ISSUE THREAD

**Issue by adam-sroka** [DigitalNutritionalAssessment/gibsonify#27]
If you select a region with a lower number, e.g 10 digits, then input the 10 digits, you lose the error text, then if you switch to a region with higher digits, the error message disappears and you can proceed without a warning unless you edit the number again

![phone_num_bug](https://user-images.githubusercontent.com/45038919/154841799-0ed0c91f-f56b-4bf6-b635-40163c22a72d.png)

**Comment by fpervaiz** [comment]
Fixed in #23 and verified by testing
